/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  APPLICATION_WITHDRAWAL_FORM_NAMES,
  APPLICATION_WITHDRAWAL_FORM_NAMES_MAP,
} from "./application-withdrawal";
import {
  ASSET_BACKED_EXHIBIT_FORM_NAMES,
  ASSET_BACKED_EXHIBIT_FORM_NAMES_MAP,
} from "./asset-backed-exhibit";
import { ATS_FORM_NAMES, ATS_FORM_NAMES_MAP } from "./ats";
import { BROKER_DEALER_FORM_NAMES, BROKER_DEALER_FORM_NAMES_MAP } from "./broker-dealer";
import {
  CORRESPONDENCE_SUBMISSION_TYPE_FORM_NAMES,
  CORRESPONDENCE_SUBMISSION_TYPE_FORM_NAMES_MAP,
} from "./correspondence-submission-types";
import { DEVELOPMENT_BANK_FORM_NAMES, DEVELOPMENT_BANK_FORM_NAMES_MAP } from "./development-bank";
import {
  EXCHANGE_LISTING_WITHDRAWAL_FORM_NAMES,
  EXCHANGE_LISTING_WITHDRAWAL_FORM_NAMES_MAP,
} from "./exchange-listing-withdrawal";
import {
  EXCHANGE_REGISTRATION_FORMS,
  EXCHANGE_REGISTRATION_FORMS_MAP,
} from "./exchange-registration";
import { EXEMPT_OFFERING_FORM_NAMES, EXEMPT_OFFERING_FORM_NAMES_MAP } from "./exempt-offerings";
import {
  FOREIGN_REGISTRATION_FORM_NAMES,
  FOREIGN_REGISTRATION_FORM_NAMES_MAP,
} from "./foreign-registration-statements";
import { INSIDER_TRADING_FORM_NAMES, INSIDER_TRADING_FORM_NAMES_MAP } from "./insider-trading";
import {
  INVESTMENT_COMPANY_FORM_NAMES,
  INVESTMENT_COMPANY_FORM_NAMES_MAP,
} from "./investment-companies";
import { LARGE_TRADER_FORM_NAMES, LARGE_TRADER_FORM_NAMES_MAP } from "./large-trader";
import {
  MISCELLANEOUS_FILINGS_FORM_NAMES,
  MISCELLANEOUS_FILINGS_FORM_NAMES_MAP,
} from "./miscellaneous-filings";
import {
  MUNICIPAL_ADVISOR_FORM_NAMES,
  MUNICIPAL_ADVISOR_FORM_NAMES_MAP,
} from "./municipal-advisor";
import { NRSRO_FORM_NAMES, NRSRO_FORM_NAMES_MAP } from "./nrsro";
import { PERIODIC_REPORT_FORM_NAMES, PERIODIC_REPORT_FORM_NAMES_MAP } from "./periodic-reports";
import { PORTAL_FORM_NAMES, PORTAL_FORM_NAMES_MAP } from "./portal";
import { PROXY_FORMS, PROXY_FORMS_MAP } from "./proxies-information-statements";
import {
  PUBLIC_UTILITY_HOLDING_COMPANY_ACT_FORMS,
  PUBLIC_UTILITY_HOLDING_COMPANY_ACT_FORMS_MAP,
} from "./public-utility-holding-company-act";
import {
  REGISTRATION_STATEMENT_FORM_NAMES,
  REGISTRATION_STATEMENT_FORM_NAMES_MAP,
} from "./registration-statements";
import {
  REGISTRATION_WITHDRAWAL_TERMINATION_FORMS,
  REGISTRATION_WITHDRAWAL_TERMINATION_FORMS_MAP,
} from "./registration-withdrawal-termination";
import { REGULATION_E_FORM_NAMES, REGULATION_E_FORM_NAMES_MAP } from "./regulation-e";
import {
  STATEMENTS_OF_OWNERSHIP_FORMS,
  STATEMENTS_OF_OWNERSHIP_FORMS_MAP,
} from "./statements-of-ownership";
import { TRANSFER_AGENT_FORM_NAMES, TRANSFER_AGENT_FORM_NAMES_MAP } from "./transfer-agent";
import {
  TRUST_INDENTURE_ACT_FORM_NAMES,
  TRUST_INDENTURE_ACT_FORM_NAMES_MAP,
} from "./trust-indenture-act";
import { FormConstructor } from "./Form";

// Combine all form names into a single array
export const ALL_FORM_NAMES = [
  ...PERIODIC_REPORT_FORM_NAMES,
  ...APPLICATION_WITHDRAWAL_FORM_NAMES,
  ...ASSET_BACKED_EXHIBIT_FORM_NAMES,
  ...ATS_FORM_NAMES,
  ...BROKER_DEALER_FORM_NAMES,
  ...CORRESPONDENCE_SUBMISSION_TYPE_FORM_NAMES,
  ...DEVELOPMENT_BANK_FORM_NAMES,
  ...EXCHANGE_LISTING_WITHDRAWAL_FORM_NAMES,
  ...EXEMPT_OFFERING_FORM_NAMES,
  ...FOREIGN_REGISTRATION_FORM_NAMES,
  ...INSIDER_TRADING_FORM_NAMES,
  ...LARGE_TRADER_FORM_NAMES,
  ...MISCELLANEOUS_FILINGS_FORM_NAMES,
  ...MUNICIPAL_ADVISOR_FORM_NAMES,
  ...NRSRO_FORM_NAMES,
  ...PORTAL_FORM_NAMES,
  ...PROXY_FORMS,
  ...PUBLIC_UTILITY_HOLDING_COMPANY_ACT_FORMS,
  ...REGISTRATION_STATEMENT_FORM_NAMES,
  ...REGISTRATION_WITHDRAWAL_TERMINATION_FORMS,
  ...REGULATION_E_FORM_NAMES,
  ...STATEMENTS_OF_OWNERSHIP_FORMS,
  ...TRANSFER_AGENT_FORM_NAMES,
  ...TRUST_INDENTURE_ACT_FORM_NAMES,
  ...INVESTMENT_COMPANY_FORM_NAMES,
  ...EXCHANGE_REGISTRATION_FORMS,
] as const;

// Export a type that represents all possible form names
export type AllForms = (typeof ALL_FORM_NAMES)[number];

const ALL_FORMS_MAP_ARRAY = [
  ...PERIODIC_REPORT_FORM_NAMES_MAP,
  ...APPLICATION_WITHDRAWAL_FORM_NAMES_MAP,
  ...ASSET_BACKED_EXHIBIT_FORM_NAMES_MAP,
  ...ATS_FORM_NAMES_MAP,
  ...BROKER_DEALER_FORM_NAMES_MAP,
  ...CORRESPONDENCE_SUBMISSION_TYPE_FORM_NAMES_MAP,
  ...DEVELOPMENT_BANK_FORM_NAMES_MAP,
  ...EXCHANGE_LISTING_WITHDRAWAL_FORM_NAMES_MAP,
  ...EXEMPT_OFFERING_FORM_NAMES_MAP,
  ...FOREIGN_REGISTRATION_FORM_NAMES_MAP,
  ...INSIDER_TRADING_FORM_NAMES_MAP,
  ...LARGE_TRADER_FORM_NAMES_MAP,
  ...MISCELLANEOUS_FILINGS_FORM_NAMES_MAP,
  ...MUNICIPAL_ADVISOR_FORM_NAMES_MAP,
  ...NRSRO_FORM_NAMES_MAP,
  ...PORTAL_FORM_NAMES_MAP,
  ...PROXY_FORMS_MAP,
  ...PUBLIC_UTILITY_HOLDING_COMPANY_ACT_FORMS_MAP,
  ...REGISTRATION_STATEMENT_FORM_NAMES_MAP,
  ...REGISTRATION_WITHDRAWAL_TERMINATION_FORMS_MAP,
  ...REGULATION_E_FORM_NAMES_MAP,
  ...STATEMENTS_OF_OWNERSHIP_FORMS_MAP,
  ...TRANSFER_AGENT_FORM_NAMES_MAP,
  ...TRUST_INDENTURE_ACT_FORM_NAMES_MAP,
  ...INVESTMENT_COMPANY_FORM_NAMES_MAP,
  ...EXCHANGE_REGISTRATION_FORMS_MAP,
] as const;

export const ALL_FORMS_MAP = new Map<string, FormConstructor>(ALL_FORMS_MAP_ARRAY);
