/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

export const US_STATE_CODE_ARRAY = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
  ["PR", "Puerto Rico"],
] as const;

export const COUNTRY_STATE_CODE_ARRAY = [
  ...US_STATE_CODE_ARRAY.map(([code, state]) => ["US", code, state, "United States"]),
  ["UM", "2J", "US Minor Outlying Islands", "United States"],
  ["GU", "GU", "Guam", "United States"],
  ["AS", "B5", "American Samoa", "United States"],
  ["MP", "1V", "Northern Mariana Islands", "United States"],
  ["VI", "VI", "Virgin Islands", "United States"],
  ["CA", "A0", "Alberta", "Canada"],
  ["CA", "A1", "British Columbia", "Canada"],
  ["CA", "A2", "Manitoba", "Canada"],
  ["CA", "A3", "New Brunswick", "Canada"],
  ["CA", "A4", "Newfoundland and Labrador", "Canada"],
  ["CA", "A5", "Nova Scotia", "Canada"],
  ["CA", "A6", "Ontario", "Canada"],
  ["CA", "A7", "Prince Edward Island", "Canada"],
  ["CA", "A8", "Quebec", "Canada"],
  ["CA", "A9", "Saskatchewan", "Canada"],
  ["CA", "B0", "Yukon", "Canada"],
  ["CA", "Z4", "Nunavut", "Canada"], // use default sec code for canada in general
  ["CA", "Z4", "Northwest Territories", "Canada"], // use default sec code for canada in general
  ["CA", "Z4", "", "Canada"], // This is the default country code for Canada
  ["AF", "B2", "", "Afghanistan"],
  ["AX", "Y6", "", "Aland Islands"],
  ["AL", "B3", "", "Albania"],
  ["DZ", "B4", "", "Algeria"],
  ["AS", "B5", "", "American Samoa"],
  ["AD", "B6", "", "Andorra"],
  ["AO", "B7", "", "Angola"],
  ["AI", "1A", "", "Anguilla"],
  ["AQ", "B8", "", "Antarctica"],
  ["AG", "B9", "", "Antigua and Barbuda"],
  ["AR", "C1", "", "Argentina"],
  ["AM", "1B", "", "Armenia"],
  ["AW", "1C", "", "Aruba"],
  ["AU", "C3", "", "Australia"],
  ["AT", "C4", "", "Austria"],
  ["AZ", "1D", "", "Azerbaijan"],
  ["BS", "C5", "", "Bahamas"],
  ["BH", "C6", "", "Bahrain"],
  ["BD", "C7", "", "Bangladesh"],
  ["BB", "C8", "", "Barbados"],
  ["BY", "1F", "", "Belarus"],
  ["BE", "C9", "", "Belgium"],
  ["BZ", "D1", "", "Belize"],
  ["BJ", "G6", "", "Benin"],
  ["BM", "D0", "", "Bermuda"],
  ["BT", "D2", "", "Bhutan"],
  ["BO", "D3", "", "Bolivia"],
  ["BA", "1E", "", "Bosnia and Herzegovina"],
  ["BW", "B1", "", "Botswana"],
  ["BV", "D4", "", "Bouvet Island"],
  ["BR", "D5", "", "Brazil"],
  ["IO", "D6", "", "British Indian Ocean Territory"],
  ["BN", "D9", "", "Brunei Darussalam"],
  ["BG", "E0", "", "Bulgaria"],
  ["BF", "X2", "", "Burkina Faso"],
  ["BI", "E2", "", "Burundi"],
  ["KH", "E3", "", "Cambodia"],
  ["CM", "E4", "", "Cameroon"],
  ["CV", "E8", "", "Cape Verde"],
  ["KY", "E9", "", "Cayman Islands"],
  ["CF", "F0", "", "Central African Republic"],
  ["TD", "F2", "", "Chad"],
  ["CL", "F3", "", "Chile"],
  ["CN", "F4", "", "China"],
  ["CX", "F6", "", "Christmas Island"],
  ["CC", "F7", "", "Cocos (Keeling) Islands"],
  ["CO", "F8", "", "Colombia"],
  ["KM", "F9", "", "Comoros"],
  ["CR", "G2", "", "Costa Rica"],
  ["CI", "L7", "", "Côte d'Ivoire"],
  ["HR", "1M", "", "Croatia"],
  ["CU", "G3", "", "Cuba"],
  ["CY", "G4", "", "Cyprus"],
  ["CZ", "2N", "", "Czech Republic"],
  ["DK", "G7", "", "Denmark"],
  ["DJ", "1G", "", "Djibouti"],
  ["DM", "G9", "", "Dominica"],
  ["DO", "G8", "", "Dominican Republic"],
  ["EC", "H1", "", "Ecuador"],
  ["EG", "H2", "", "Egypt"],
  ["SV", "H3", "", "El Salvador"],
  ["GQ", "H4", "", "Equatorial Guinea"],
  ["ER", "1J", "", "Eritrea"],
  ["EE", "1H", "", "Estonia"],
  ["ET", "H5", "", "Ethiopia"],
  ["FK", "H7", "", "Falkland Islands (Malvinas)"],
  ["FO", "H6", "", "Faroe Islands"],
  ["FJ", "H8", "", "Fiji"],
  ["FI", "H9", "", "Finland"],
  ["FR", "I0", "", "France"],
  ["GF", "I3", "", "French Guiana"],
  ["PF", "I4", "", "French Polynesia"],
  ["TF", "2C", "", "French Southern Territories"],
  ["GA", "I5", "", "Gabon"],
  ["GM", "I6", "", "Gambia"],
  ["GE", "2Q", "", "Georgia (Country)"],
  ["DE", "2M", "", "Germany"],
  ["GH", "J0", "", "Ghana"],
  ["GI", "J1", "", "Gibraltar"],
  ["GR", "J3", "", "Greece"],
  ["GL", "J4", "", "Greenland"],
  ["GD", "J5", "", "Grenada"],
  ["GP", "J6", "", "Guadeloupe"],
  ["GU", "GU", "", "Guam"],
  ["GT", "J8", "", "Guatemala"],
  ["GG", "Y7", "", "Guernsey"],
  ["GN", "J9", "", "Guinea"],
  ["GW", "S0", "", "Guinea-Bissau"],
  ["GY", "K0", "", "Guyana"],
  ["HT", "K1", "", "Haiti"],
  ["HM", "K4", "", "Heard Island and McDonald Islands"],
  ["VA", "X4", "", "Holy See (Vatican City State)"],
  ["HN", "K2", "", "Honduras"],
  ["HK", "K3", "", "Hong Kong"],
  ["HU", "K5", "", "Hungary"],
  ["IS", "K6", "", "Iceland"],
  ["IN", "K7", "", "India"],
  ["ID", "K8", "", "Indonesia"],
  ["IR", "K9", "", "Iran, Islamic Republic of"],
  ["IQ", "L0", "", "Iraq"],
  ["IE", "L2", "", "Ireland"],
  ["IM", "Y8", "", "Isle of Man"],
  ["IL", "L3", "", "Israel"],
  ["IT", "L6", "", "Italy"],
  ["JM", "L8", "", "Jamaica"],
  ["JP", "M0", "", "Japan"],
  ["JE", "Y9", "", "Jersey"],
  ["JO", "M2", "", "Jordan"],
  ["KZ", "1P", "", "Kazakhstan"],
  ["KE", "M3", "", "Kenya"],
  ["KI", "J2", "", "Kiribati"],
  ["KP", "M4", "", "Korea, Democratic People's Republic of"],
  ["KR", "M5", "", "Korea, Republic of"],
  ["KW", "M6", "", "Kuwait"],
  ["KG", "1N", "", "Kyrgyzstan"],
  ["LA", "M7", "", "Lao People's Democratic Republic"],
  ["LV", "1R", "", "Latvia"],
  ["LB", "M8", "", "Lebanon"],
  ["LS", "M9", "", "Lesotho"],
  ["LR", "N0", "", "Liberia"],
  ["LY", "N1", "", "Libya"],
  ["LI", "N2", "", "Liechtenstein"],
  ["LT", "1Q", "", "Lithuania"],
  ["LU", "N4", "", "Luxembourg"],
  ["MO", "N5", "", "Macau"],
  ["MK", "1U", "", "North Macedonia"],
  ["MG", "N6", "", "Madagascar"],
  ["MW", "N7", "", "Malawi"],
  ["MY", "N8", "", "Malaysia"],
  ["MV", "N9", "", "Maldives"],
  ["ML", "O0", "", "Mali"],
  ["MT", "O1", "", "Malta"],
  ["MH", "1T", "", "Marshall Islands"],
  ["MQ", "O2", "", "Martinique"],
  ["MR", "O3", "", "Mauritania"],
  ["MU", "O4", "", "Mauritius"],
  ["YT", "2P", "", "Mayotte"],
  ["MX", "O5", "", "Mexico"],
  ["FM", "1K", "", "Micronesia, Federated States of"],
  ["MD", "1S", "", "Moldova, Republic of"],
  ["MC", "O9", "", "Monaco"],
  ["MN", "P0", "", "Mongolia"],
  ["ME", "Z5", "", "Montenegro"],
  ["MS", "P1", "", "Montserrat"],
  ["MA", "P2", "", "Morocco"],
  ["MZ", "P3", "", "Mozambique"],
  ["MM", "E1", "", "Myanmar"],
  ["NA", "T6", "", "Namibia"],
  ["NR", "P5", "", "Nauru"],
  ["NP", "P6", "", "Nepal"],
  ["NL", "P7", "", "Netherlands"],
  ["AN", "P8", "", "Netherlands Antilles"],
  ["NC", "1W", "", "New Caledonia"],
  ["NZ", "Q2", "", "New Zealand"],
  ["NI", "Q3", "", "Nicaragua"],
  ["NE", "Q4", "", "Niger"],
  ["NG", "Q5", "", "Nigeria"],
  ["NU", "Q6", "", "Niue"],
  ["NF", "Q7", "", "Norfolk Island"],
  ["NO", "Q8", "", "Norway"],
  ["OM", "P4", "", "Oman"],
  ["PK", "R0", "", "Pakistan"],
  ["PW", "1Y", "", "Palau"],
  ["PS", "1X", "", "Palestinian Territory, Occupied"],
  ["PA", "R1", "", "Panama"],
  ["PG", "R2", "", "Papua New Guinea"],
  ["PY", "R4", "", "Paraguay"],
  ["PE", "R5", "", "Peru"],
  ["PH", "R6", "", "Philippines"],
  ["PN", "R8", "", "Pitcairn"],
  ["PL", "R9", "", "Poland"],
  ["PT", "S1", "", "Portugal"],
  ["QA", "S3", "", "Qatar"],
  ["RE", "S4", "", "Reunion"],
  ["RO", "S5", "", "Romania"],
  ["RU", "1Z", "", "Russian Federation"],
  ["RW", "S6", "", "Rwanda"],
  ["BL", "Z0", "", "Saint Barthélemy"],
  ["SH", "U8", "", "Saint Helena"],
  ["KN", "U7", "", "Saint Kitts and Nevis"],
  ["LC", "U9", "", "Saint Lucia"],
  ["MF", "Z1", "", "Saint Martin"],
  ["PM", "V0", "", "Saint Pierre and Miquelon"],
  ["VC", "V1", "", "Saint Vincent and the Grenadines"],
  ["WS", "Y0", "", "Samoa"],
  ["SM", "S8", "", "San Marino"],
  ["ST", "S9", "", "Sao Tome and Principe"],
  ["SA", "T0", "", "Saudi Arabia"],
  ["SN", "T1", "", "Senegal"],
  ["RS", "Z2", "", "Serbia"],
  ["SC", "T2", "", "Seychelles"],
  ["SL", "T8", "", "Sierra Leone"],
  ["SG", "U0", "", "Singapore"],
  ["SK", "2B", "", "Slovakia"],
  ["SI", "2A", "", "Slovenia"],
  ["SB", "D7", "", "Solomon Islands"],
  ["SO", "U1", "", "Somalia"],
  ["ZA", "T3", "", "South Africa"],
  ["GS", "1L", "", "South Georgia and the South Sandwich Islands"],
  ["ES", "U3", "", "Spain"],
  ["LK", "F1", "", "Sri Lanka"],
  ["SD", "V2", "", "Sudan"],
  ["SR", "V3", "", "Suriname"],
  ["SJ", "L9", "", "Svalbard and Jan Mayen"],
  ["SZ", "V6", "", "Eswatini"],
  ["SE", "V7", "", "Sweden"],
  ["CH", "V8", "", "Switzerland"],
  ["SY", "V9", "", "Syrian Arab Republic"],
  ["TW", "F5", "", "Taiwan"],
  ["TJ", "2D", "", "Tajikistan"],
  ["TZ", "W0", "", "Tanzania, United Republic of"],
  ["TH", "W1", "", "Thailand"],
  ["TL", "Z3", "", "Timor-Leste"],
  ["TG", "W2", "", "Togo"],
  ["TK", "W3", "", "Tokelau"],
  ["TO", "W4", "", "Tonga"],
  ["TT", "W5", "", "Trinidad and Tobago"],
  ["TN", "W6", "", "Tunisia"],
  ["TR", "W8", "", "Turkey"],
  ["TM", "2E", "", "Turkmenistan"],
  ["TC", "W7", "", "Turks and Caicos Islands"],
  ["TV", "2G", "", "Tuvalu"],
  ["UG", "W9", "", "Uganda"],
  ["UA", "2H", "", "Ukraine"],
  ["AE", "C0", "", "United Arab Emirates"],
  ["GB", "X0", "", "United Kingdom"],
  ["UY", "X3", "", "Uruguay"],
  ["UZ", "2K", "", "Uzbekistan"],
  ["VU", "2L", "", "Vanuatu"],
  ["VE", "X5", "", "Venezuela"],
  ["VN", "Q1", "", "Viet Nam"],
  ["VG", "D8", "", "Virgin Islands, British"],
  ["WF", "X8", "", "Wallis and Futuna"],
  ["EH", "U5", "", "Western Sahara"],
  ["YE", "T7", "", "Yemen"],
  ["ZM", "Y4", "", "Zambia"],
  ["ZW", "Y5", "", "Zimbabwe"],
  ["ZZ", "XX", "", "Unknown"],
] as const;

export const SEC_STATE_CODE_ARRAY = COUNTRY_STATE_CODE_ARRAY.map(
  ([iso, sec, state, country]) => sec
);

export const ISO_COUNTRY_CODE_ARRAY = Array.from(
  new Set(COUNTRY_STATE_CODE_ARRAY.map(([iso, sec, state, country]) => iso))
);

// Keyword to country mapping
export const KEYWORD_STATE_OR_COUNTRY_MAP = [
  ["TORONTO", "A0"],
  ["VANCOUVER", "A0"],
  ["NORTH VANCOUVER", "A0"],
  ["CALGARY", "A0"],
  ["KANATA", "A0"],
  ["MONTREAL", "A0"],
  ["ST-LAURENT", "A0"],
  ["SAN JUAN", "Puerto Rico"],
  ["RINCON", "Puerto Rico"],
  ["LONDON", "X0"],
  ["EDINBURGH", "X0"],
  ["MANCHESTER", "X0"],
  ["REIGATE", "X0"],
  ["SHANGHAI", "F4"],
  ["BEIJING", "F4"],
  ["HANGZHOU", "F4"],
  ["GUANGZHOU", "F4"],
  ["DONGGUAN", "F4"],
  ["XIAMEN", "F4"],
  ["SHENZHEN", "F4"],
  ["CHENGDU", "F4"],
  ["WUHAN", "F4"],
  ["HONG KONG", "K3"],
  ["KOWLOON", "K3"],
  ["SINGAPORE", "U0"],
  ["GRAND CAYMAN", "E9"],
  ["GEORGE TOWN", "E9"],
  ["CAMANA BAY", "E9"],
  ["ZURICH", "V8"],
  ["BAAR", "V8"],
  ["BASEL", "V8"],
  ["ZUG", "V8"],
  ["LUXEMBOURG", "N4"],
  ["PARIS", "I0"],
  ["MUNICH", "2M"],
  ["HEPPENHEIM", "2M"],
  ["MILANO", "L6"],
  ["LUCCA", "L6"],
  ["THE HAGUE", "P7"],
  ["AMSTERDAM", "P7"],
  ["OSLO", "Q8"],
  ["LYSAKER", "Q8"],
  ["HOERSHOLM", "G7"],
  ["BUDAPEST", "K5"],
  ["MIGDAL HAEMEK", "L3"],
  ["HERZILIYA PITUACH", "L3"],
  ["BNEI BRAK", "L3"],
  ["DUBAI", "C0"],
  ["ABU DHABI", "C0"],
  ["SAU PAULO", "D5"],
  ["SAO PAULO", "D5"],
  ["MEXICO CITY", "O5"],
  ["SYDNEY", "C3"],
  ["MELBOURNE", "C3"],
  ["TOKYO", "M0"],
  ["DUBLIN", "L2"],
  ["MADRID", "U3"],
  ["WARSZAWA", "R9"],
  ["BRATISLAVA", "2B"],
  ["STOCKHOLM", "V7"],
  ["NACKA", "V7"],
  ["AKTAU", "1P"],
  ["KUALA LUMPUR", "N8"],
  ["ST. HELIER", "Y9"],
  ["ST. PETER PORT", "Y7"],
  ["NASSAU", "C5"],
  ["LYFORD BAHAMAS", "C5"],
  ["NEW PROVIDENCE", "C5"],
  ["YEREVAN", "1B"],
  ["HELSINKI", "H9"],
  ["TAMPERE", "H9"],
] as const;
