/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

export const US_STATE_CODE_ARRAY = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
  ["PR", "Puerto Rico"],
] as const;

export const COUNTRY_STATE_CODE_ARRAY = [
  ...US_STATE_CODE_ARRAY.map(([code, state]) => ["US", code, state, "United States"]),
  ["UM", "2J", "US Minor Outlying Islands", "United States"],
  ["GU", "GU", "Guam", "United States"],
  ["AS", "B5", "American Samoa", "United States"],
  ["MP", "1V", "Northern Mariana Islands", "United States"],
  ["VI", "VI", "Virgin Islands", "United States"],
  ["CA", "A0", "Alberta", "Canada"],
  ["CA", "A1", "British Columbia", "Canada"],
  ["CA", "A2", "Manitoba", "Canada"],
  ["CA", "A3", "New Brunswick", "Canada"],
  ["CA", "A4", "Newfoundland and Labrador", "Canada"],
  ["CA", "A5", "Nova Scotia", "Canada"],
  ["CA", "A6", "Ontario", "Canada"],
  ["CA", "A7", "Prince Edward Island", "Canada"],
  ["CA", "A8", "Quebec", "Canada"],
  ["CA", "A9", "Saskatchewan", "Canada"],
  ["CA", "B0", "Yukon", "Canada"],
  ["CA", "Z4", "Nunavut", "Canada"], // use default sec code for canada in general
  ["CA", "Z4", "Northwest Territories", "Canada"], // use default sec code for canada in general
  ["CA", "Z4", "", "Canada"], // This is the default country code for Canada
  ["AF", "B2", "", "Afghanistan"],
  ["AX", "Y6", "", "Aland Islands"],
  ["AL", "B3", "", "Albania"],
  ["DZ", "B4", "", "Algeria"],
  ["AS", "B5", "", "American Samoa"],
  ["AD", "B6", "", "Andorra"],
  ["AO", "B7", "", "Angola"],
  ["AI", "1A", "", "Anguilla"],
  ["AQ", "B8", "", "Antarctica"],
  ["AG", "B9", "", "Antigua and Barbuda"],
  ["AR", "C1", "", "Argentina"],
  ["AM", "1B", "", "Armenia"],
  ["AW", "1C", "", "Aruba"],
  ["AU", "C3", "", "Australia"],
  ["AT", "C4", "", "Austria"],
  ["AZ", "1D", "", "Azerbaijan"],
  ["BS", "C5", "", "Bahamas"],
  ["BH", "C6", "", "Bahrain"],
  ["BD", "C7", "", "Bangladesh"],
  ["BB", "C8", "", "Barbados"],
  ["BY", "1F", "", "Belarus"],
  ["BE", "C9", "", "Belgium"],
  ["BZ", "D1", "", "Belize"],
  ["BJ", "G6", "", "Benin"],
  ["BM", "D0", "", "Bermuda"],
  ["BT", "D2", "", "Bhutan"],
  ["BO", "D3", "", "Bolivia"],
  ["BA", "1E", "", "Bosnia and Herzegovina"],
  ["BW", "B1", "", "Botswana"],
  ["BV", "D4", "", "Bouvet Island"],
  ["BR", "D5", "", "Brazil"],
  ["IO", "D6", "", "British Indian Ocean Territory"],
  ["BN", "D9", "", "Brunei Darussalam"],
  ["BG", "E0", "", "Bulgaria"],
  ["BF", "X2", "", "Burkina Faso"],
  ["BI", "E2", "", "Burundi"],
  ["KH", "E3", "", "Cambodia"],
  ["CM", "E4", "", "Cameroon"],
  ["CV", "E8", "", "Cape Verde"],
  ["KY", "E9", "", "Cayman Islands"],
  ["CF", "F0", "", "Central African Republic"],
  ["TD", "F2", "", "Chad"],
  ["CL", "F3", "", "Chile"],
  ["CN", "F4", "", "China"],
  ["CX", "F6", "", "Christmas Island"],
  ["CC", "F7", "", "Cocos (Keeling) Islands"],
  ["CO", "F8", "", "Colombia"],
  ["KM", "F9", "", "Comoros"],
  ["CR", "G2", "", "Costa Rica"],
  ["CI", "L7", "", "Côte d'Ivoire"],
  ["HR", "1M", "", "Croatia"],
  ["CU", "G3", "", "Cuba"],
  ["CY", "G4", "", "Cyprus"],
  ["CZ", "2N", "", "Czech Republic"],
  ["DK", "G7", "", "Denmark"],
  ["DJ", "1G", "", "Djibouti"],
  ["DM", "G9", "", "Dominica"],
  ["DO", "G8", "", "Dominican Republic"],
  ["EC", "H1", "", "Ecuador"],
  ["EG", "H2", "", "Egypt"],
  ["SV", "H3", "", "El Salvador"],
  ["GQ", "H4", "", "Equatorial Guinea"],
  ["ER", "1J", "", "Eritrea"],
  ["EE", "1H", "", "Estonia"],
  ["ET", "H5", "", "Ethiopia"],
  ["FK", "H7", "", "Falkland Islands (Malvinas)"],
  ["FO", "H6", "", "Faroe Islands"],
  ["FJ", "H8", "", "Fiji"],
  ["FI", "H9", "", "Finland"],
  ["FR", "I0", "", "France"],
  ["GF", "I3", "", "French Guiana"],
  ["PF", "I4", "", "French Polynesia"],
  ["TF", "2C", "", "French Southern Territories"],
  ["GA", "I5", "", "Gabon"],
  ["GM", "I6", "", "Gambia"],
  ["GE", "2Q", "", "Georgia (Country)"],
  ["DE", "2M", "", "Germany"],
  ["GH", "J0", "", "Ghana"],
  ["GI", "J1", "", "Gibraltar"],
  ["GR", "J3", "", "Greece"],
  ["GL", "J4", "", "Greenland"],
  ["GD", "J5", "", "Grenada"],
  ["GP", "J6", "", "Guadeloupe"],
  ["GU", "GU", "", "Guam"],
  ["GT", "J8", "", "Guatemala"],
  ["GG", "Y7", "", "Guernsey"],
  ["GN", "J9", "", "Guinea"],
  ["GW", "S0", "", "Guinea-Bissau"],
  ["GY", "K0", "", "Guyana"],
  ["HT", "K1", "", "Haiti"],
  ["HM", "K4", "", "Heard Island and McDonald Islands"],
  ["VA", "X4", "", "Holy See (Vatican City State)"],
  ["HN", "K2", "", "Honduras"],
  ["HK", "K3", "", "Hong Kong"],
  ["HU", "K5", "", "Hungary"],
  ["IS", "K6", "", "Iceland"],
  ["IN", "K7", "", "India"],
  ["ID", "K8", "", "Indonesia"],
  ["IR", "K9", "", "Iran, Islamic Republic of"],
  ["IQ", "L0", "", "Iraq"],
  ["IE", "L2", "", "Ireland"],
  ["IM", "Y8", "", "Isle of Man"],
  ["IL", "L3", "", "Israel"],
  ["IT", "L6", "", "Italy"],
  ["JM", "L8", "", "Jamaica"],
  ["JP", "M0", "", "Japan"],
  ["JE", "Y9", "", "Jersey"],
  ["JO", "M2", "", "Jordan"],
  ["KZ", "1P", "", "Kazakhstan"],
  ["KE", "M3", "", "Kenya"],
  ["KI", "J2", "", "Kiribati"],
  ["KP", "M4", "", "Korea, Democratic People's Republic of"],
  ["KR", "M5", "", "Korea, Republic of"],
  ["KW", "M6", "", "Kuwait"],
  ["KG", "1N", "", "Kyrgyzstan"],
  ["LA", "M7", "", "Lao People's Democratic Republic"],
  ["LV", "1R", "", "Latvia"],
  ["LB", "M8", "", "Lebanon"],
  ["LS", "M9", "", "Lesotho"],
  ["LR", "N0", "", "Liberia"],
  ["LY", "N1", "", "Libya"],
  ["LI", "N2", "", "Liechtenstein"],
  ["LT", "1Q", "", "Lithuania"],
  ["LU", "N4", "", "Luxembourg"],
  ["MO", "N5", "", "Macau"],
  ["MK", "1U", "", "North Macedonia"],
  ["MG", "N6", "", "Madagascar"],
  ["MW", "N7", "", "Malawi"],
  ["MY", "N8", "", "Malaysia"],
  ["MV", "N9", "", "Maldives"],
  ["ML", "O0", "", "Mali"],
  ["MT", "O1", "", "Malta"],
  ["MH", "1T", "", "Marshall Islands"],
  ["MQ", "O2", "", "Martinique"],
  ["MR", "O3", "", "Mauritania"],
  ["MU", "O4", "", "Mauritius"],
  ["YT", "2P", "", "Mayotte"],
  ["MX", "O5", "", "Mexico"],
  ["FM", "1K", "", "Micronesia, Federated States of"],
  ["MD", "1S", "", "Moldova, Republic of"],
  ["MC", "O9", "", "Monaco"],
  ["MN", "P0", "", "Mongolia"],
  ["ME", "Z5", "", "Montenegro"],
  ["MS", "P1", "", "Montserrat"],
  ["MA", "P2", "", "Morocco"],
  ["MZ", "P3", "", "Mozambique"],
  ["MM", "E1", "", "Myanmar"],
  ["NA", "T6", "", "Namibia"],
  ["NR", "P5", "", "Nauru"],
  ["NP", "P6", "", "Nepal"],
  ["NL", "P7", "", "Netherlands"],
  ["AN", "P8", "", "Netherlands Antilles"],
  ["NC", "1W", "", "New Caledonia"],
  ["NZ", "Q2", "", "New Zealand"],
  ["NI", "Q3", "", "Nicaragua"],
  ["NE", "Q4", "", "Niger"],
  ["NG", "Q5", "", "Nigeria"],
  ["NU", "Q6", "", "Niue"],
  ["NF", "Q7", "", "Norfolk Island"],
  ["NO", "Q8", "", "Norway"],
  ["OM", "P4", "", "Oman"],
  ["PK", "R0", "", "Pakistan"],
  ["PW", "1Y", "", "Palau"],
  ["PS", "1X", "", "Palestinian Territory, Occupied"],
  ["PA", "R1", "", "Panama"],
  ["PG", "R2", "", "Papua New Guinea"],
  ["PY", "R4", "", "Paraguay"],
  ["PE", "R5", "", "Peru"],
  ["PH", "R6", "", "Philippines"],
  ["PN", "R8", "", "Pitcairn"],
  ["PL", "R9", "", "Poland"],
  ["PT", "S1", "", "Portugal"],
  ["QA", "S3", "", "Qatar"],
  ["RE", "S4", "", "Reunion"],
  ["RO", "S5", "", "Romania"],
  ["RU", "1Z", "", "Russian Federation"],
  ["RW", "S6", "", "Rwanda"],
  ["BL", "Z0", "", "Saint Barthélemy"],
  ["SH", "U8", "", "Saint Helena"],
  ["KN", "U7", "", "Saint Kitts and Nevis"],
  ["LC", "U9", "", "Saint Lucia"],
  ["MF", "Z1", "", "Saint Martin"],
  ["PM", "V0", "", "Saint Pierre and Miquelon"],
  ["VC", "V1", "", "Saint Vincent and the Grenadines"],
  ["WS", "Y0", "", "Samoa"],
  ["SM", "S8", "", "San Marino"],
  ["ST", "S9", "", "Sao Tome and Principe"],
  ["SA", "T0", "", "Saudi Arabia"],
  ["SN", "T1", "", "Senegal"],
  ["RS", "Z2", "", "Serbia"],
  ["SC", "T2", "", "Seychelles"],
  ["SL", "T8", "", "Sierra Leone"],
  ["SG", "U0", "", "Singapore"],
  ["SK", "2B", "", "Slovakia"],
  ["SI", "2A", "", "Slovenia"],
  ["SB", "D7", "", "Solomon Islands"],
  ["SO", "U1", "", "Somalia"],
  ["ZA", "T3", "", "South Africa"],
  ["GS", "1L", "", "South Georgia and the South Sandwich Islands"],
  ["ES", "U3", "", "Spain"],
  ["LK", "F1", "", "Sri Lanka"],
  ["SD", "V2", "", "Sudan"],
  ["SR", "V3", "", "Suriname"],
  ["SJ", "L9", "", "Svalbard and Jan Mayen"],
  ["SZ", "V6", "", "Eswatini"],
  ["SE", "V7", "", "Sweden"],
  ["CH", "V8", "", "Switzerland"],
  ["SY", "V9", "", "Syrian Arab Republic"],
  ["TW", "F5", "", "Taiwan"],
  ["TJ", "2D", "", "Tajikistan"],
  ["TZ", "W0", "", "Tanzania, United Republic of"],
  ["TH", "W1", "", "Thailand"],
  ["TL", "Z3", "", "Timor-Leste"],
  ["TG", "W2", "", "Togo"],
  ["TK", "W3", "", "Tokelau"],
  ["TO", "W4", "", "Tonga"],
  ["TT", "W5", "", "Trinidad and Tobago"],
  ["TN", "W6", "", "Tunisia"],
  ["TR", "W8", "", "Turkey"],
  ["TM", "2E", "", "Turkmenistan"],
  ["TC", "W7", "", "Turks and Caicos Islands"],
  ["TV", "2G", "", "Tuvalu"],
  ["UG", "W9", "", "Uganda"],
  ["UA", "2H", "", "Ukraine"],
  ["AE", "C0", "", "United Arab Emirates"],
  ["GB", "X0", "", "United Kingdom"],
  ["UY", "X3", "", "Uruguay"],
  ["UZ", "2K", "", "Uzbekistan"],
  ["VU", "2L", "", "Vanuatu"],
  ["VE", "X5", "", "Venezuela"],
  ["VN", "Q1", "", "Viet Nam"],
  ["VG", "D8", "", "Virgin Islands, British"],
  ["WF", "X8", "", "Wallis and Futuna"],
  ["EH", "U5", "", "Western Sahara"],
  ["YE", "T7", "", "Yemen"],
  ["ZM", "Y4", "", "Zambia"],
  ["ZW", "Y5", "", "Zimbabwe"],
  ["ZZ", "XX", "", "Unknown"],
] as const;

export const SEC_STATE_CODE_ARRAY = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "PR",
  "2J",
  "GU",
  "B5",
  "1V",
  "VI",
  "A0",
  "A1",
  "A2",
  "A3",
  "A4",
  "A5",
  "A6",
  "A7",
  "A8",
  "A9",
  "B0",
  "Z4",
  "B2",
  "Y6",
  "B3",
  "B4",
  "B6",
  "B7",
  "1A",
  "B8",
  "B9",
  "C1",
  "1B",
  "1C",
  "C3",
  "C4",
  "1D",
  "C5",
  "C6",
  "C7",
  "C8",
  "1F",
  "C9",
  "D1",
  "G6",
  "D0",
  "D2",
  "D3",
  "1E",
  "B1",
  "D4",
  "D5",
  "D6",
  "D9",
  "E0",
  "X2",
  "E2",
  "E3",
  "E4",
  "E8",
  "E9",
  "F0",
  "F2",
  "F3",
  "F4",
  "F6",
  "F7",
  "F8",
  "F9",
  "G2",
  "L7",
  "1M",
  "G3",
  "G4",
  "2N",
  "G7",
  "1G",
  "G9",
  "G8",
  "H1",
  "H2",
  "H3",
  "H4",
  "1J",
  "1H",
  "H5",
  "H7",
  "H6",
  "H8",
  "H9",
  "I0",
  "I3",
  "I4",
  "2C",
  "I5",
  "I6",
  "2Q",
  "2M",
  "J0",
  "J1",
  "J3",
  "J4",
  "J5",
  "J6",
  "J8",
  "Y7",
  "J9",
  "S0",
  "K0",
  "K1",
  "K4",
  "X4",
  "K2",
  "K3",
  "K5",
  "K6",
  "K7",
  "K8",
  "K9",
  "L0",
  "L2",
  "Y8",
  "L3",
  "L6",
  "L8",
  "M0",
  "Y9",
  "M2",
  "1P",
  "M3",
  "J2",
  "M4",
  "M5",
  "M6",
  "1N",
  "M7",
  "1R",
  "M8",
  "M9",
  "N0",
  "N1",
  "N2",
  "1Q",
  "N4",
  "N5",
  "1U",
  "N6",
  "N7",
  "N8",
  "N9",
  "O0",
  "O1",
  "1T",
  "O2",
  "O3",
  "O4",
  "2P",
  "O5",
  "1K",
  "1S",
  "O9",
  "P0",
  "Z5",
  "P1",
  "P2",
  "P3",
  "E1",
  "T6",
  "P5",
  "P6",
  "P7",
  "P8",
  "1W",
  "Q2",
  "Q3",
  "Q4",
  "Q5",
  "Q6",
  "Q7",
  "Q8",
  "P4",
  "R0",
  "1Y",
  "1X",
  "R1",
  "R2",
  "R4",
  "R5",
  "R6",
  "R8",
  "R9",
  "S1",
  "S3",
  "S4",
  "S5",
  "1Z",
  "S6",
  "Z0",
  "U8",
  "U7",
  "U9",
  "Z1",
  "V0",
  "V1",
  "Y0",
  "S8",
  "S9",
  "T0",
  "T1",
  "Z2",
  "T2",
  "T8",
  "U0",
  "2B",
  "2A",
  "D7",
  "U1",
  "T3",
  "1L",
  "U3",
  "F1",
  "V2",
  "V3",
  "L9",
  "V6",
  "V7",
  "V8",
  "V9",
  "F5",
  "2D",
  "W0",
  "W1",
  "Z3",
  "W2",
  "W3",
  "W4",
  "W5",
  "W6",
  "W8",
  "2E",
  "W7",
  "2G",
  "W9",
  "2H",
  "C0",
  "X0",
  "X3",
  "2K",
  "2L",
  "X5",
  "Q1",
  "D8",
  "X8",
  "U5",
  "T7",
  "Y4",
  "Y5",
  "XX",
] as const;

export const ISO_COUNTRY_CODE_ARRAY = [
  "US",
  "UM",
  "GU",
  "AS",
  "MP",
  "VI",
  "CA",
  "AF",
  "AX",
  "AL",
  "DZ",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BA",
  "BW",
  "BV",
  "BR",
  "IO",
  "BN",
  "BG",
  "BF",
  "BI",
  "KH",
  "CM",
  "CV",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CX",
  "CC",
  "CO",
  "KM",
  "CR",
  "CI",
  "HR",
  "CU",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GR",
  "GL",
  "GD",
  "GP",
  "GT",
  "GG",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "VA",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MK",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "AN",
  "NC",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "QA",
  "RE",
  "RO",
  "RU",
  "RW",
  "BL",
  "SH",
  "KN",
  "LC",
  "MF",
  "PM",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "GS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SJ",
  "SZ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VG",
  "WF",
  "EH",
  "YE",
  "ZM",
  "ZW",
  "ZZ",
] as const;

// Keyword to country mapping
export const KEYWORD_STATE_OR_COUNTRY_MAP = [
  ["TORONTO", "A0"],
  ["VANCOUVER", "A0"],
  ["NORTH VANCOUVER", "A0"],
  ["CALGARY", "A0"],
  ["KANATA", "A0"],
  ["MONTREAL", "A0"],
  ["ST-LAURENT", "A0"],
  ["SAN JUAN", "Puerto Rico"],
  ["RINCON", "Puerto Rico"],
  ["LONDON", "X0"],
  ["EDINBURGH", "X0"],
  ["MANCHESTER", "X0"],
  ["REIGATE", "X0"],
  ["SHANGHAI", "F4"],
  ["BEIJING", "F4"],
  ["HANGZHOU", "F4"],
  ["GUANGZHOU", "F4"],
  ["DONGGUAN", "F4"],
  ["XIAMEN", "F4"],
  ["SHENZHEN", "F4"],
  ["CHENGDU", "F4"],
  ["WUHAN", "F4"],
  ["HONG KONG", "K3"],
  ["KOWLOON", "K3"],
  ["SINGAPORE", "U0"],
  ["GRAND CAYMAN", "E9"],
  ["GEORGE TOWN", "E9"],
  ["CAMANA BAY", "E9"],
  ["ZURICH", "V8"],
  ["BAAR", "V8"],
  ["BASEL", "V8"],
  ["ZUG", "V8"],
  ["LUXEMBOURG", "N4"],
  ["PARIS", "I0"],
  ["MUNICH", "2M"],
  ["HEPPENHEIM", "2M"],
  ["MILANO", "L6"],
  ["LUCCA", "L6"],
  ["THE HAGUE", "P7"],
  ["AMSTERDAM", "P7"],
  ["OSLO", "Q8"],
  ["LYSAKER", "Q8"],
  ["HOERSHOLM", "G7"],
  ["BUDAPEST", "K5"],
  ["MIGDAL HAEMEK", "L3"],
  ["HERZILIYA PITUACH", "L3"],
  ["BNEI BRAK", "L3"],
  ["DUBAI", "C0"],
  ["ABU DHABI", "C0"],
  ["SAU PAULO", "D5"],
  ["SAO PAULO", "D5"],
  ["MEXICO CITY", "O5"],
  ["SYDNEY", "C3"],
  ["MELBOURNE", "C3"],
  ["TOKYO", "M0"],
  ["DUBLIN", "L2"],
  ["MADRID", "U3"],
  ["WARSZAWA", "R9"],
  ["BRATISLAVA", "2B"],
  ["STOCKHOLM", "V7"],
  ["NACKA", "V7"],
  ["AKTAU", "1P"],
  ["KUALA LUMPUR", "N8"],
  ["ST. HELIER", "Y9"],
  ["ST. PETER PORT", "Y7"],
  ["NASSAU", "C5"],
  ["LYFORD BAHAMAS", "C5"],
  ["NEW PROVIDENCE", "C5"],
  ["YEREVAN", "1B"],
  ["HELSINKI", "H9"],
  ["TAMPERE", "H9"],
] as const;
