import type {
  AutoGeneratedKeys,
  CoveringIndexQueryOptions,
  DataPortSchemaObject,
  DeleteSearchCriteria,
  FromSchema,
  InsertEntity,
  ITabularStorage,
  JoinedRow,
  JoinSpec,
  JoinType,
  Page,
  PageRequest,
  QueryOptions,
  SearchCriteria,
  SimplifyPrimaryKey,
  TabularChangePayload,
  TabularEventListener,
  TabularEventName,
  TabularEventParameters,
  TabularSubscribeOptions,
  TypedArraySchemaOptions,
} from "workglow";

/**
 * Wraps an {@link ITabularStorage} and silently no-ops all write operations.
 * Read operations (get, getAll, query, getBulk, getOffsetPage, records, pages, size) are
 * forwarded to the underlying storage so that dry-run commands can still
 * inspect existing data.
 */
export class ReadOnlyTabularStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  PrimaryKey = SimplifyPrimaryKey<Entity, PrimaryKeyNames>,
  InsertType = InsertEntity<Entity, AutoGeneratedKeys<Schema>>,
> implements ITabularStorage<Schema, PrimaryKeyNames, Entity, PrimaryKey, InsertType> {
  constructor(
    private readonly inner: ITabularStorage<Schema, PrimaryKeyNames, Entity, PrimaryKey, InsertType>
  ) {}

  // ── writes (no-op) ─────────────────────────────────────────────────

  async put(_value: InsertType): Promise<Entity> {
    return _value as unknown as Entity;
  }

  async putBulk(values: InsertType[]): Promise<Entity[]> {
    return values as unknown as Entity[];
  }

  async updateWhere(
    _match: SearchCriteria<Entity>,
    _patch: Partial<Entity>
  ): Promise<Entity | undefined> {
    // Read-only: no row is updated.
    return undefined;
  }

  async delete(_key: PrimaryKey | Entity): Promise<void> {}

  async deleteAll(): Promise<void> {}

  async deleteSearch(_criteria: DeleteSearchCriteria<Entity>): Promise<void> {}

  async setupDatabase(): Promise<void> {}

  // ── reads (forwarded) ──────────────────────────────────────────────

  get(key: PrimaryKey): Promise<Entity | undefined> {
    return this.inner.get(key);
  }

  getAll(options?: QueryOptions<Entity>): Promise<Entity[] | undefined> {
    return this.inner.getAll(options);
  }

  size(): Promise<number> {
    return this.inner.size();
  }

  count(criteria?: SearchCriteria<Entity>): Promise<number> {
    return this.inner.count(criteria);
  }

  getBulk(keys: readonly PrimaryKey[]): Promise<Entity[]> {
    return this.inner.getBulk(keys);
  }

  getOffsetPage(offset: number, limit: number): Promise<Entity[] | undefined> {
    return this.inner.getOffsetPage(offset, limit);
  }

  getPage(request?: PageRequest<Entity>): Promise<Page<Entity>> {
    return this.inner.getPage(request);
  }

  queryPage(
    criteria: SearchCriteria<Entity>,
    request?: PageRequest<Entity>
  ): Promise<Page<Entity>> {
    return this.inner.queryPage(criteria, request);
  }

  records(pageSize?: number): AsyncGenerator<Entity, void, undefined> {
    return this.inner.records(pageSize);
  }

  pages(pageSize?: number): AsyncGenerator<Entity[], void, undefined> {
    return this.inner.pages(pageSize);
  }

  query(
    criteria: SearchCriteria<Entity>,
    options?: QueryOptions<Entity>
  ): Promise<Entity[] | undefined> {
    return this.inner.query(criteria, options);
  }

  queryIndex<K extends keyof Entity & string>(
    criteria: SearchCriteria<Entity>,
    options: CoveringIndexQueryOptions<Entity, K>
  ): Promise<Pick<Entity, K>[]> {
    return this.inner.queryIndex(criteria, options);
  }

  /**
   * A join is a read, so it forwards like every other read here. The write
   * guard this wrapper exists for is unaffected: nothing in a join mutates.
   */
  join<R, T extends JoinType>(
    spec: JoinSpec<Entity, R, T>,
    right: ITabularStorage<any, any, R, any, any>
  ): Promise<JoinedRow<Entity, R, T>[]> {
    return this.inner.join(spec, right);
  }

  // ── transactions (no-op wrapper) ───────────────────────────────────
  // Run `fn` against this read-only wrapper so writes inside continue to
  // no-op; reads still hit the underlying storage. No real DB transaction
  // is opened because there is nothing to commit or roll back.
  withTransaction<T>(fn: (tx: this) => Promise<T>): Promise<T> {
    return fn(this);
  }

  // ── events (forwarded) ────────────────────────────────────────────

  on<Event extends TabularEventName>(
    name: Event,
    fn: TabularEventListener<Event, PrimaryKey, Entity>
  ): void {
    this.inner.on(name, fn);
  }

  off<Event extends TabularEventName>(
    name: Event,
    fn: TabularEventListener<Event, PrimaryKey, Entity>
  ): void {
    this.inner.off(name, fn);
  }

  emit<Event extends TabularEventName>(
    name: Event,
    ...args: TabularEventParameters<Event, PrimaryKey, Entity>
  ): void {
    this.inner.emit(name, ...args);
  }

  once<Event extends TabularEventName>(
    name: Event,
    fn: TabularEventListener<Event, PrimaryKey, Entity>
  ): void {
    this.inner.once(name, fn);
  }

  waitOn<Event extends TabularEventName>(
    name: Event
  ): Promise<TabularEventParameters<Event, PrimaryKey, Entity>> {
    return this.inner.waitOn(name);
  }

  subscribeToChanges(
    callback: (change: TabularChangePayload<Entity>) => void,
    options?: TabularSubscribeOptions
  ): () => void {
    return this.inner.subscribeToChanges(callback, options);
  }

  // ── lifecycle ─────────────────────────────────────────────────────

  destroy(): void {
    this.inner.destroy();
  }

  [Symbol.dispose](): void {
    this.inner[Symbol.dispose]();
  }

  [Symbol.asyncDispose](): Promise<void> {
    return this.inner[Symbol.asyncDispose]();
  }
}
